// select form
const form = document.getElementById("astroForm");

// quotes array
const quotes = [
    "Today is a lucky day for you.",
    "A new opportunity will appear soon.",
    "Patience will bring great rewards.",
    "Your hard work will soon pay off.",
    "Trust your intuition today.",
    "Something exciting is coming your way.",
    "A small step today leads to big success.",
    "Confidence will guide you forward.",
    "Unexpected good news may arrive.",
    "Focus on what truly matters.",
    "Someone will appreciate your kindness.",
    "A challenge will make you stronger.",
    "Creativity will open new doors.",
    "Today is a good day to learn something new.",
    "Your energy will inspire others.",
    "A positive attitude will change everything.",
    "Believe in your abilities.",
    "A meaningful conversation is coming.",
    "You will solve a problem easily.",
    "Take time to relax and recharge.",
    "A new friendship may begin.",
    "Your ideas will shine today.",
    "Success is closer than you think.",
    "Stay patient and calm.",
    "An opportunity for growth is near.",
    "You will overcome a difficulty.",
    "Your determination will bring victory.",
    "A surprising event may happen today.",
    "Kindness will return to you.",
    "Trust the process of life.",
    "A bold decision will help you.",
    "You will discover something valuable.",
    "Your courage will inspire others.",
    "A dream may start becoming reality.",
    "Stay open to new experiences.",
    "Today will bring positive energy.",
    "Your focus will lead to success.",
    "A new path will appear soon.",
    "You will receive helpful advice.",
    "A happy moment is waiting for you.",
    "Your confidence will attract success.",
    "Take a chance on something new.",
    "Good fortune is near.",
    "A small effort will make a big difference.",
    "Your creativity will impress others.",
    "Something you wished for may happen.",
    "A good opportunity will come your way.",
    "Stay strong during challenges.",
    "You will gain useful knowledge today.",
    "Positive changes are coming.",
    "A calm mind will guide you.",
    "You will find a solution quickly.",
    "Your determination will be rewarded.",
    "A pleasant surprise is waiting.",
    "You will make someone smile today.",
    "Success will come with patience.",
    "A new idea will inspire you.",
    "You will meet someone interesting.",
    "Your effort will not go unnoticed.",
    "Today is perfect for starting something new.",
    "You will learn something important.",
    "Trust yourself more.",
    "A peaceful moment will refresh you.",
    "Your talents will shine.",
    "A helpful person may appear.",
    "You will gain confidence today.",
    "Something exciting may happen soon.",
    "Stay optimistic about the future.",
    "Your kindness will create happiness.",
    "A challenge will turn into success.",
    "You will discover a new skill.",
    "Your positive mindset will help you.",
    "You will accomplish a goal soon.",
    "A new adventure may begin.",
    "Your ideas will be appreciated.",
    "Today is a day for progress.",
    "You will feel motivated today.",
    "A good decision will lead to success.",
    "You will inspire someone today.",
    "Stay focused on your goals.",
    "Your energy will attract positivity.",
    "A joyful moment is coming.",
    "You will receive good news soon.",
    "A dream may come true.",
    "Your patience will be rewarded.",
    "A fresh start is possible today.",
    "You will overcome a fear.",
    "Your creativity will grow.",
    "A meaningful change is ahead.",
    "You will make progress today.",
    "Something wonderful is about to happen.",
    "Stay confident in your path.",
    "You will find motivation today.",
    "A positive surprise is coming.",
    "You will achieve something important.",
    "Your efforts will bring success.",
    "A bright future awaits you."
];
const zodiacSigns = [
    "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"
];
const vicimCard = [
    "You sometimes overthink situations too much.",
    "You may doubt yourself even when you are capable.",
    "You often avoid difficult decisions.",
    "You sometimes rely too much on others for validation.",
    "You may struggle with patience.",
    "You sometimes hold onto the past longer than needed.",
    "You may hesitate to take risks.",
    "You can be too hard on yourself.",
    "You sometimes expect quick results.",
    "You may avoid confronting problems directly.",

    "You sometimes let emotions control decisions.",
    "You may struggle with consistency.",
    "You sometimes procrastinate important tasks.",
    "You may depend too much on comfort zones.",
    "You sometimes fear failure too strongly.",
    "You may underestimate your own abilities.",
    "You sometimes avoid responsibility when things get difficult.",
    "You may struggle to say no to others.",
    "You sometimes seek approval too much.",
    "You may delay important changes.",

    "You sometimes focus more on problems than solutions.",
    "You may compare yourself to others too often.",
    "You sometimes overanalyze small issues.",
    "You may struggle with discipline.",
    "You sometimes expect motivation instead of building habits.",
    "You may ignore your own potential.",
    "You sometimes doubt your decisions.",
    "You may avoid uncomfortable growth.",
    "You sometimes worry about others' opinions.",
    "You may hold yourself back with fear.",

    "You sometimes hesitate when opportunity appears.",
    "You may struggle with focus.",
    "You sometimes take criticism personally.",
    "You may become discouraged too easily.",
    "You sometimes avoid stepping outside your comfort zone.",
    "You may struggle with long-term commitment.",
    "You sometimes lose motivation quickly.",
    "You may focus on perfection instead of progress.",
    "You sometimes expect results without patience.",
    "You may struggle to stay organized.",

    "You sometimes underestimate how capable you are.",
    "You may avoid difficult conversations.",
    "You sometimes overthink simple decisions.",
    "You may feel stuck even when solutions exist.",
    "You sometimes focus too much on past mistakes.",
    "You may ignore small improvements.",
    "You sometimes worry about failure too much.",
    "You may struggle with self-discipline.",
    "You sometimes wait for the right moment too long.",
    "You may delay taking action.",

    "You sometimes lose confidence when challenges appear.",
    "You may hesitate to trust your instincts.",
    "You sometimes rely too much on motivation.",
    "You may struggle to stay consistent.",
    "You sometimes feel overwhelmed by small problems.",
    "You may doubt your progress.",
    "You sometimes avoid taking initiative.",
    "You may expect quick success.",
    "You sometimes lose focus easily.",
    "You may hesitate when leadership is needed.",

    "You sometimes underestimate the power of persistence.",
    "You may struggle to accept criticism.",
    "You sometimes avoid responsibility for mistakes.",
    "You may focus too much on comfort.",
    "You sometimes hesitate to ask for help.",
    "You may overthink future outcomes.",
    "You sometimes struggle to prioritize.",
    "You may lose motivation after setbacks.",
    "You sometimes hold unrealistic expectations.",
    "You may worry about outcomes you cannot control.",

    "You sometimes doubt yourself more than necessary.",
    "You may struggle to maintain routines.",
    "You sometimes avoid challenging goals.",
    "You may underestimate how much effort success requires.",
    "You sometimes let small failures discourage you.",
    "You may struggle with patience during growth.",
    "You sometimes compare your journey to others.",
    "You may underestimate your resilience.",
    "You sometimes focus on weaknesses instead of strengths.",
    "You may struggle with self-belief.",

    "You sometimes wait for confidence before taking action.",
    "You may hesitate when facing uncertainty.",
    "You sometimes hold back your ideas.",
    "You may struggle to trust your progress.",
    "You sometimes avoid uncomfortable truths.",
    "You may underestimate your ability to adapt.",
    "You sometimes focus on short-term comfort.",
    "You may delay important decisions.",
    "You sometimes ignore your own growth.",
    "You may forget how capable you truly are."
]

form.addEventListener("submit", (e) => {
    e.preventDefault()
    Name = document.querySelector("#name").value;
    const Randomqoute = Math.floor(Math.random() * quotes.length + 1)
    quote = quotes[Randomqoute];

    const RandomZodiac = Math.floor(Math.random() * zodiacSigns.length + 1)
    Zodiac = zodiacSigns[RandomZodiac];

    const RandomVictimQoutes = Math.floor(Math.random() * vicimCard.length + 1)
    victimQoutes = vicimCard[RandomVictimQoutes]
    document.querySelector("#result").innerHTML = `Hello ${Name} \n ${victimQoutes}.\nYour ZodiacSign is ${Zodiac}. \nqouet of the Day - ${quote}.`
})


